# Generated by Django 4.2.2 on 2023-08-28 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('body', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('body', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preference_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('body', models.CharField(max_length=200)),
                ('adress', models.CharField(default='adress', max_length=20)),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment_people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='usernname', max_length=100)),
                ('title', models.ForeignKey(db_column='title', default='title', on_delete=django.db.models.deletion.CASCADE, to='dream.recruitment', to_field='title')),
            ],
        ),
        migrations.AddField(
            model_name='recruitment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dream.recruitment_tag'),
        ),
        migrations.CreateModel(
            name='Preference_people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='usernname', max_length=100)),
                ('title', models.ForeignKey(db_column='title', default='title', on_delete=django.db.models.deletion.CASCADE, to='dream.preference', to_field='title')),
            ],
        ),
        migrations.CreateModel(
            name='Preference_GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='usernname', max_length=100)),
                ('message', models.TextField(default='default_message', max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('title', models.ForeignKey(db_column='title', default='title', on_delete=django.db.models.deletion.CASCADE, to='dream.preference', to_field='title')),
            ],
        ),
        migrations.AddField(
            model_name='preference',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dream.preference_tag'),
        ),
        migrations.CreateModel(
            name='Agenda_people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='usernname', max_length=100)),
                ('title', models.ForeignKey(db_column='title', default='title', on_delete=django.db.models.deletion.CASCADE, to='dream.agenda', to_field='title')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda_GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='usernname', max_length=100)),
                ('message', models.TextField(default='default_message', max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('title', models.ForeignKey(db_column='title', default='title', on_delete=django.db.models.deletion.CASCADE, to='dream.agenda', to_field='title')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dream.agenda_tag'),
        ),
    ]
