# Generated by Django 4.2.2 on 2023-10-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='body',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
