# Generated by Django 4.2.2 on 2023-11-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0002_alter_preference_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
